# Notre image de base donnée dans le projet
FROM python:3.12-slim

# Installer procps : nécessaire pour la commande "uptime" utilisée par collector.py
RUN apt-get update && apt-get install -y --no-install-recommends procps \
    && rm -rf /var/lib/apt/lists/*

# Travailler dans le dossier /app du conteneur
WORKDIR /app

# Copier uniquement requirements.txt d'abord (optimisation du cache Docker)
COPY requirements.txt .

# Installer les dépendances liées au fichier requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copier le reste du code de l'application
COPY . .

# Créer un utilisateur non-root et basculer dessus, pour ne pas exécuter le code en root
RUN useradd --create-home appuser
USER appuser

# uvicorn lance API FastAPI quand l'image est démarrée / reload est utilisée 
# pour recharger automatiquement l'application en cas de modification du code.
CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]